import "bootstrap/dist/css/bootstrap.min.css";
import "antd/dist/reset.css";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { loadMessages } from "@/i18n/loadMessages";
import "./globals.scss";
import HomeLayout from "@/components/layout/HomeLayout";
import ReduxProvider from "@/components/providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }) {
  const resolvedParams = await params;
  const { locale } = resolvedParams ?? {};

  if (!locale || !routing.locales.includes(locale)) {
    notFound();
  }

  setRequestLocale(locale);

  let messages;
  try {
    messages = await loadMessages(locale);
  } catch (error) {
    notFound();
  }

  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={direction}
      data-dir={direction}
      data-scroll-behavior="smooth"
    >
      <body dir={direction} className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxProvider>
            <HomeLayout>{children}</HomeLayout>
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
